/// Flutter icons Customicons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicons
///      fonts:
///       - asset: fonts/Customicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Customicons {
  Customicons._();

  static const _kFontFam = 'Customicons';
  static const String? _kFontPkg = null;

  static const IconData fa6_solid_mosque = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthicons_ambulance = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthicons_ambulatory_clinic = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_buildings_fill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluent_vote_20_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthicons_mobile_clinic = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_round_train = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ion_home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_about = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nusuk_logo_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ph_hospital_fill = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solar_buildings_2_bold = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
